from apolnx.teste.apo import apo02
with open('/totvs/protheus/bin/apphianny/appserver.ini','r') as arquivo:
    arquivoini = arquivo.readlines()
    for linha in arquivoini:
        if apo02 in linha:
            print("foi encontrado apo02")
            with open('/totvs/protheus/bin/apphianny/appserver.ini','w') as arquivos:
                for linha in arquivoini:
                    if apo02 in linha:
                        arquivos.write('[hianny]\n'
'canacceptdebugger=1\n'
'dateformat=default\n'
'enablenewadv=0\n'
'helpserver=help.outsourcing.com.br/p11\n'
'killstack=1\n'
'localdbextension=.dtc\n'
'localfiles=ctree\n'
'maxlocks=10000\n'
'multprofile=1\n'
'pictformat=default\n'
'regionallanguage=bra\n'
'rootpath=/totvs/protheus/protheus_data\n'
'rpocustom=/totvs/protheus/apo/apohianny/custom.rpo\n'
'rpodb=top\n'
'rpolanguage=multi\n'
'rpoversion=120\n'
'sourcepath=/totvs/protheus/apo/apohianny\n'
'specialkey=HOMOLLNX\n'
'startpath=/system/\n'
'topmemomega=1\n'
'trace=0\n'
'[homologacao]\n'
'canacceptdebugger=1\n'
'dateformat=default\n'
'enablenewadv=0\n'
'helpserver=help.outsourcing.com.br/p11\n'
'killstack=1\n'
'localdbextension=.dtc\n'
'localfiles=ctree\n'
'maxlocks=10000\n'
'multprofile=1\n'
'pictformat=default\n'
'regionallanguage=bra\n'
'rootpath=/totvs/protheus/protheus_data\n'
'rpocustom=/totvs/protheus/apo/apo02/custom.rpo\n'
'rpodb=top\n'
'rpolanguage=multi\n'
'rpoversion=120\n'
'sourcepath=/totvs/protheus/apo/apo02\n'
'specialkey=HOMOLLNX\n'
'startpath=/system/\n'
'topmemomega=1\n'
'trace=0\n'
'Theme=Sunset\n'
'[general]\n'
'app_environment=homologacao\n'
'canrunjobs=0\n'
'consolefile=/totvs/protheus/bin/log/apphianny.log\n'
'consolelog=1\n'
'consolemaxsize=10485760\n'
'ctreepreimg=0\n'
'debugthreadusedmemory=0\n'
'floatingpointprecise=1\n'
'installpath=/totvs/protheus\n'
'maxstringsize=50\n'
'Theme=Sunset\n'
'[dbaccess]\n'
'alias=protheus_homol\n'
'database=oracle\n'
'memomega=1\n'
'port=7890\n'
'protheusonly=0\n'
'server=localhost\n'
'[drivers]\n'
'active=tcp\n'
'multiprotocolportsecure=0\n'
'multiprotocolport=1\n'
'[tcp]\n'
'type=tcpip\n'
'port=10020\n'
'[licenseclient]\n'
'server=10.192.0.90\n'
'port=5557\n'
'[tds]\n'
'allowapplypatch=*\n'
'enabledisconnectuser=*\n'
'enablesendmessage=*\n'
'enableblocknewconnection=*\n'
'enablestopserver=*)\n')